/*
 The MIT License (MIT)

 Copyright (c) 2016 Martin Braun

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in all
 copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 SOFTWARE.
 */
package com.github.s4ke.moar.json;

import com.github.s4ke.moar.MoaPattern;

import org.junit.Test;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;

/**
 * @author Martin Braun
 */
public class MoarJSONSerializerTest {

	@Test
	public void testJSONSerialization() {
		MoaPattern pattern = MoaPattern.compile( "^(?<toast>[a-z]b[^b]\\w)\\k<toast>.$" );
		String jsonString = MoarJSONSerializer.toJSON( pattern );
		System.out.println( jsonString );
		assertTrue( pattern.matcher( "abcdabcde" ).matches() );

		MoaPattern fromJSON = MoarJSONSerializer.fromJSON( jsonString );
		System.out.println( "\n" + MoarJSONSerializer.toJSON( fromJSON ) );
		assertTrue( fromJSON.matcher( "abcdabcde" ).matches() );

		assertEquals( jsonString, MoarJSONSerializer.toJSON( fromJSON ) );
	}

	//TODO: maybe test JSON serialization of MOAs generated by the DSL?

}
